// Generate the tiny synthetic model fixture used by CI.
//
// The real model is a separate npm package, so until it publishes (and on any
// checkout without it) every semantic test skips — the council's lead_dev
// called that out: the layer would ship with no CI coverage at all.
//
// This builds a miniature model in the SAME payload format: 8 dimensions, a
// two-dozen-token vocabulary, and hand-placed vectors that put related words
// in the same direction. That makes semantic retrieval deterministic and
// assertable without any downloaded weights. It does NOT replace the golden
// vectors — those pin numerical fidelity against the real model and can only
// run once it resolves. This pins the plumbing: load, validate, tokenize,
// chunk, embed, store, score, fuse.
//
//   npx tsx scripts/make-tiny-model.ts

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = join(process.cwd(), 'tests', 'fixtures', 'tiny-model', 'model');
mkdirSync(OUT, { recursive: true });

const DIM = 8;

// Three deliberate clusters. Words in a cluster share a direction, so a query
// built from cluster A retrieves a document built from cluster A even with no
// shared vocabulary — the exact property the semantic layer exists for.
const AUTH = ['credentials', 'expired', 'registry', 'rejected', 'upload',
              'authentication', 'lapsed', 'package', 'push', 'refused'];
const HOUSE = ['kitchen', 'sink', 'dishes', 'full'];
const GLUE = ['the', 'and', 'was', 'so', 'a', 'of', 'is', 'note'];

const vocab: Record<string, number> = { '[PAD]': 0, '[UNK]': 1 };
let next = 2;
for (const w of [...AUTH, ...HOUSE, ...GLUE]) vocab[w] = next++;
const vocabSize = next;

const rows: number[][] = Array.from({ length: vocabSize }, () => new Array(DIM).fill(0));
const put = (word: string, vec: number[]) => { rows[vocab[word]!] = vec; };

// Slight per-word jitter so no two words are identical, but the cluster
// direction dominates — mean-pooling a sentence lands on its cluster.
AUTH.forEach((w, i) => put(w, [120, 10, 0, (i % 5) * 4, 0, 0, (i % 3) * 3, 0]));
HOUSE.forEach((w, i) => put(w, [0, 0, 120, 10, (i % 3) * 4, 0, 0, 0]));
// Glue words are near-zero so they neither carry nor cancel meaning.
GLUE.forEach((w, i) => put(w, [0, 0, 0, 0, 0, 8, (i % 2) * 4, 6]));

const flat = new Int8Array(vocabSize * DIM);
for (let r = 0; r < vocabSize; r += 1) {
  for (let d = 0; d < DIM; d += 1) flat[r * DIM + d] = rows[r]![d]!;
}
writeFileSync(join(OUT, 'embeddings.int8.bin'), Buffer.from(flat.buffer));

const scales = new Float32Array(vocabSize).fill(1);
writeFileSync(join(OUT, 'scales.f32.bin'), Buffer.from(scales.buffer));

writeFileSync(join(OUT, 'tokenizer.json'), JSON.stringify({
  version: '1.0',
  // Same component triple the real payload declares — embed.ts refuses
  // anything else, so the fixture exercises that validation too.
  normalizer: {
    type: 'BertNormalizer',
    clean_text: true,
    handle_chinese_chars: true,
    strip_accents: null,
    lowercase: true,
  },
  pre_tokenizer: { type: 'BertPreTokenizer' },
  model: {
    type: 'WordPiece',
    unk_token: '[UNK]',
    continuing_subword_prefix: '##',
    max_input_chars_per_word: 100,
    vocab,
  },
}, null, 2) + '\n');

writeFileSync(join(OUT, 'model.json'), JSON.stringify({
  format: 'veto-model/1',
  upstream: { model_id: 'synthetic/tiny-test-model', revision: 'fixture', license: 'n/a' },
  vocab_size: vocabSize,
  dim: DIM,
  quantization: { dtype: 'int8', scheme: 'per-row symmetric', dequantize: 'row_f32 = int8_row * scale[row]' },
  inference: {
    add_special_tokens: false,
    pooling: 'mean',
    normalize: true,
    normalize_epsilon: 1e-32,
    empty_input: 'zero vector of length dim',
    per_token_weights: null,
  },
  tokenizer: {
    file: 'tokenizer.json',
    model_type: 'WordPiece',
    strip_accents_effective: true,
  },
  note: 'SYNTHETIC TEST FIXTURE — not a real model. Generated by scripts/make-tiny-model.ts',
}, null, 2) + '\n');

console.log(`wrote ${vocabSize} x ${DIM} fixture to ${OUT}`);
