// Pure-JS Model2Vec inference — the semantic half of transcript recall.
//
// The model is frozen DATA, not an API: a quantized matrix plus a vocabulary.
// So this is a reimplementation against a pinned contract, not a translation
// of upstream code. The contract lives in the model package's `model.json`
// and every assumption below is asserted at load time, because the failure
// mode we care about is not a crash — it is plausible-looking wrong vectors.
//
// Correctness is pinned by tests/transcripts/embed.test.ts, which replays the
// golden vectors shipped alongside the weights (fixed text -> expected
// output, generated by the reference Python implementation in
// scripts/repack-model.py). If this file drifts, those fail.
//
// Zero dependencies, and nothing here runs at import: the model is resolved
// on first use and never at server boot (condition A2), so a missing or
// corrupt copy degrades search to BM25 instead of taking Veto down.

import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const _require = createRequire(import.meta.url);

/** Dim of the shipped table. Cross-checked against the header on load. */
const EXPECTED_FORMAT = 'veto-model/1';
// model2vec normalizes with this epsilon; matching it keeps golden vectors
// bit-comparable for zero-norm inputs instead of producing NaN.
const NORM_EPSILON = 1e-32;

type Header = {
  format: string;
  upstream: { model_id: string; revision: string };
  vocab_size: number;
  dim: number;
  inference: {
    add_special_tokens: boolean;
    pooling: string;
    normalize: boolean;
    per_token_weights: unknown;
  };
  tokenizer: { strip_accents_effective: boolean };
};

type Model = {
  header: Header;
  dim: number;
  /** Row-major int8 table, vocab_size * dim. */
  table: Int8Array;
  /** One scale per row: row_f32 = table[row] * scales[row]. */
  scales: Float32Array;
  vocab: Map<string, number>;
  unkId: number | undefined;
  prefix: string;
  maxWordChars: number;
  lowercase: boolean;
  stripAccents: boolean;
  cleanText: boolean;
  handleChineseChars: boolean;
};

let _model: Model | undefined;

/** Package root holding the payload. Env override exists for tests and for
 *  local work before the model package is published. */
function modelDir(): string {
  if (process.env.VETO_MODEL_DIR) return join(process.env.VETO_MODEL_DIR, 'model');
  // The package's exports map points at the header; the payload sits beside it.
  return dirname(_require.resolve('@jigyasudham/veto-model/model.json'));
}

// ---------------------------------------------------------------------------
// BertNormalizer
//
// Order is upstream's and matters: clean -> CJK spacing -> accents -> case.
// ---------------------------------------------------------------------------

// Upstream treats tab/newline/CR as text, not control chars, and strips the
// rest of the C categories along with NUL and the replacement char.
const CONTROL = /\p{C}/u;
const PUNCT = /[!-/:-@[-`{-~]|\p{P}/u;

function isControl(ch: string): boolean {
  if (ch === '\t' || ch === '\n' || ch === '\r') return false;
  return CONTROL.test(ch);
}

function isWhitespace(ch: string): boolean {
  return ch === ' ' || ch === '\t' || ch === '\n' || ch === '\r' || /\s/u.test(ch);
}

// The CJK blocks BERT spaces out so every ideograph becomes its own word.
// Hiragana/katakana are deliberately absent upstream — they tokenize as runs.
function isChinese(cp: number): boolean {
  return (
    (cp >= 0x4e00 && cp <= 0x9fff) ||
    (cp >= 0x3400 && cp <= 0x4dbf) ||
    (cp >= 0x20000 && cp <= 0x2a6df) ||
    (cp >= 0x2a700 && cp <= 0x2b73f) ||
    (cp >= 0x2b740 && cp <= 0x2b81f) ||
    (cp >= 0x2b820 && cp <= 0x2ceaf) ||
    (cp >= 0xf900 && cp <= 0xfaff) ||
    (cp >= 0x2f800 && cp <= 0x2fa1f)
  );
}

function normalize(text: string, m: Model): string {
  let out = text;

  if (m.cleanText) {
    let buf = '';
    for (const ch of out) {
      // NUL and U+FFFD as escapes, matching upstream's filter. Literals
      // here embed raw control bytes and make tools treat this file as binary.
      if (ch === '\u0000' || ch === '\uFFFD' || isControl(ch)) continue;
      buf += isWhitespace(ch) ? ' ' : ch;
    }
    out = buf;
  }

  if (m.handleChineseChars) {
    let buf = '';
    for (const ch of out) {
      const cp = ch.codePointAt(0)!;
      buf += isChinese(cp) ? ` ${ch} ` : ch;
    }
    out = buf;
  }

  // `strip_accents: null` in tokenizer.json does NOT mean "off" — upstream
  // resolves it to the value of `lowercase`. Reading the null literally is
  // the silent-divergence bug this whole file is most likely to have; it only
  // shows on accented text, so the golden set carries "café naïve résumé".
  if (m.stripAccents) out = out.normalize('NFD').replace(/\p{Mn}/gu, '');

  if (m.lowercase) out = out.toLowerCase();

  return out;
}

// ---------------------------------------------------------------------------
// BertPreTokenizer — split on whitespace, then isolate punctuation as its own
// word. "Isolated" means the punctuation is KEPT as a token, not discarded.
// ---------------------------------------------------------------------------

function preTokenize(text: string): string[] {
  const words: string[] = [];
  for (const chunk of text.split(/\s+/u)) {
    if (!chunk) continue;
    let cur = '';
    for (const ch of chunk) {
      if (PUNCT.test(ch)) {
        if (cur) { words.push(cur); cur = ''; }
        words.push(ch);
      } else {
        cur += ch;
      }
    }
    if (cur) words.push(cur);
  }
  return words;
}

// ---------------------------------------------------------------------------
// WordPiece — greedy longest-match-first, continuation pieces carry "##".
// Operates on code points, not UTF-16 units, so astral characters (emoji)
// are matched and length-capped as single characters like upstream does.
// ---------------------------------------------------------------------------

function wordPiece(word: string, m: Model, out: number[]): void {
  const chars = Array.from(word);
  if (chars.length > m.maxWordChars) {
    if (m.unkId !== undefined) out.push(m.unkId);
    return;
  }

  const pieces: number[] = [];
  let start = 0;
  while (start < chars.length) {
    let end = chars.length;
    let id: number | undefined;
    while (start < end) {
      const sub = (start > 0 ? m.prefix : '') + chars.slice(start, end).join('');
      id = m.vocab.get(sub);
      if (id !== undefined) break;
      end -= 1;
    }
    // No prefix of the remainder is in the vocabulary: upstream discards every
    // piece found so far and emits a single UNK for the whole word.
    if (id === undefined) {
      if (m.unkId !== undefined) out.push(m.unkId);
      return;
    }
    pieces.push(id);
    start = end;
  }
  for (const p of pieces) out.push(p);
}

/** Token ids for `text`, with no special tokens added (the shipped contract). */
export function tokenizeForEmbedding(text: string, model = load()): number[] {
  const ids: number[] = [];
  for (const word of preTokenize(normalize(text, model))) wordPiece(word, model, ids);

  // Upstream drops UNK entirely rather than pooling it (model2vec model.py:166,
  // "necessary for word-level models"), so an out-of-vocab word contributes
  // nothing instead of dragging every vector toward a shared UNK row. Filtering
  // here rather than skipping at emit time matches upstream for the odd case of
  // a literal "[UNK]" in the input, which WordPiece would otherwise keep.
  return model.unkId === undefined ? ids : ids.filter((id) => id !== model.unkId);
}

// ---------------------------------------------------------------------------
// Load
// ---------------------------------------------------------------------------

function load(): Model {
  if (_model) return _model;

  const dir = modelDir();
  const header = JSON.parse(readFileSync(join(dir, 'model.json'), 'utf8')) as Header;

  if (header.format !== EXPECTED_FORMAT) {
    throw new Error(`veto-model: unsupported payload format ${header.format} (expected ${EXPECTED_FORMAT})`);
  }
  // model2vec multiplies token rows by an optional per-token weight vector
  // before pooling. potion-base-8M ships none, and this implementation pools
  // unweighted — so a model that DOES ship them must not load silently.
  if (header.inference.per_token_weights != null) {
    throw new Error('veto-model: payload declares per-token weights, which this implementation does not apply');
  }
  if (header.inference.add_special_tokens) {
    throw new Error('veto-model: payload expects special tokens, which this implementation does not add');
  }
  if (header.inference.pooling !== 'mean' || !header.inference.normalize) {
    throw new Error(`veto-model: unsupported inference contract (${header.inference.pooling}, normalize=${header.inference.normalize})`);
  }

  const { vocab_size: vocabSize, dim } = header;
  const tableBuf = readFileSync(join(dir, 'embeddings.int8.bin'));
  const scaleBuf = readFileSync(join(dir, 'scales.f32.bin'));
  if (tableBuf.length !== vocabSize * dim) {
    throw new Error(`veto-model: table is ${tableBuf.length} bytes, expected ${vocabSize * dim}`);
  }
  if (scaleBuf.length !== vocabSize * 4) {
    throw new Error(`veto-model: scales are ${scaleBuf.length} bytes, expected ${vocabSize * 4}`);
  }

  const tok = JSON.parse(readFileSync(join(dir, 'tokenizer.json'), 'utf8')) as {
    normalizer?: { type?: string; lowercase?: boolean; strip_accents?: boolean | null; clean_text?: boolean; handle_chinese_chars?: boolean };
    pre_tokenizer?: { type?: string };
    model?: { type?: string; vocab?: Record<string, number>; unk_token?: string; continuing_subword_prefix?: string; max_input_chars_per_word?: number };
  };
  const norm = tok.normalizer ?? {};
  const tm = tok.model ?? {};
  if (tm.type !== 'WordPiece' || norm.type !== 'BertNormalizer' || tok.pre_tokenizer?.type !== 'BertPreTokenizer') {
    throw new Error(`veto-model: unsupported tokenizer (${norm.type} / ${tok.pre_tokenizer?.type} / ${tm.type})`);
  }

  const vocab = new Map<string, number>(Object.entries(tm.vocab ?? {}));
  if (vocab.size !== vocabSize) {
    throw new Error(`veto-model: vocab has ${vocab.size} entries, table has ${vocabSize} rows`);
  }

  const lowercase = norm.lowercase !== false;
  const model: Model = {
    header,
    dim,
    table: new Int8Array(tableBuf.buffer, tableBuf.byteOffset, tableBuf.length),
    // Little-endian float32; Node is LE on every supported platform, and a
    // byteOffset-aligned view would be brittle, so copy through a DataView.
    scales: readScales(scaleBuf, vocabSize),
    vocab,
    unkId: tm.unk_token ? vocab.get(tm.unk_token) : undefined,
    prefix: tm.continuing_subword_prefix ?? '##',
    maxWordChars: tm.max_input_chars_per_word ?? 100,
    lowercase,
    // Resolve null the way upstream does — see normalize().
    stripAccents: norm.strip_accents == null ? lowercase : norm.strip_accents,
    cleanText: norm.clean_text !== false,
    handleChineseChars: norm.handle_chinese_chars !== false,
  };

  if (model.stripAccents !== header.tokenizer.strip_accents_effective) {
    throw new Error('veto-model: resolved strip_accents disagrees with the payload header');
  }

  _model = model;
  return model;
}

function readScales(buf: Buffer, n: number): Float32Array {
  const view = new DataView(buf.buffer, buf.byteOffset, buf.length);
  const out = new Float32Array(n);
  for (let i = 0; i < n; i++) out[i] = view.getFloat32(i * 4, true);
  return out;
}

// ---------------------------------------------------------------------------
// Embed
// ---------------------------------------------------------------------------

/**
 * Embed `text` into a unit-length vector.
 *
 * Gather each token's row, dequantize it by that row's scale, mean-pool, then
 * L2-normalize. Text with no tokens (empty or punctuation-free-of-vocab)
 * yields the zero vector rather than NaN — upstream's behaviour, and the
 * reason the epsilon is in the denominator.
 */
export function embed(text: string, model = load()): Float32Array {
  const ids = tokenizeForEmbedding(text, model);
  const { dim, table, scales } = model;
  const out = new Float32Array(dim);
  if (ids.length === 0) return out;

  for (const id of ids) {
    const base = id * dim;
    const scale = scales[id]!;
    for (let d = 0; d < dim; d++) out[d]! += table[base + d]! * scale;
  }

  let norm = 0;
  for (let d = 0; d < dim; d++) {
    out[d]! /= ids.length;
    norm += out[d]! * out[d]!;
  }
  norm = Math.sqrt(norm) + NORM_EPSILON;
  for (let d = 0; d < dim; d++) out[d]! /= norm;

  return out;
}

/** Cosine similarity of two unit vectors — a dot product, given the inputs. */
export function cosine(a: Float32Array, b: Float32Array): number {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += a[i]! * b[i]!;
  return s;
}

/** True when the model package resolves and its payload passes validation. */
export function embeddingsAvailable(): boolean {
  try { load(); return true; } catch { return false; }
}

/** Upstream model id + revision of the loaded payload, for recall provenance. */
export function modelProvenance(): { model_id: string; revision: string } {
  const { upstream } = load().header;
  return { model_id: upstream.model_id, revision: upstream.revision };
}

/** Drop the cached table. Tests only — production loads once per process. */
export function resetModelCache(): void {
  _model = undefined;
}
